In [ ]:
pip install numpy

In [ ]:
import numpy as np
j = np.array([["Fizza","Bilal","Abdullah","Abdul rehman"],
 [4,"Bilal","Abdullah","Abdul rehman"],
  ["Fizza","Bilal","Abdullah","Abdul rehman"]])
c = np.array([[56465,286872,36525,328523586,6858423],[36368,7828,652,2365326,2365235],[327826,34256326,322365,32736,7656]])
print(j)
print(c)
print(j.shape)
print(j.ndim)
print(j.size)


[['Fizza' 'Bilal' 'Abdullah' 'Abdul rehman']
 ['4' 'Bilal' 'Abdullah' 'Abdul rehman']
 ['Fizza' 'Bilal' 'Abdullah' 'Abdul rehman']]
[[    56465    286872     36525 328523586   6858423]
 [    36368      7828       652   2365326   2365235]
 [   327826  34256326    322365     32736      7656]]
(3, 4)
2
12


list into array
 memory kam speed zaya proccessing zayada

one dimension
elements separated by comma  
shapes = row or column
numpy = data set ki shape , dimensions 1d , 2d
single 1d
2 3 rows h to 2d dimensions
size
different types ki array = work

In [ ]:
import numpy as np
a = np.array([[[["Maan","abdullah","bilal","fizza"],
              ["Maan","abdullah","bilal","fizza"],
               ["Maan","abdullah","bilal","fizza"]]]])
print(a)

print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)


[[[['Maan' 'abdullah' 'bilal' 'fizza']
   ['Maan' 'abdullah' 'bilal' 'fizza']
   ['Maan' 'abdullah' 'bilal' 'fizza']]]]
4
(1, 1, 3, 4)
12
<U8


In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
x= np.arange(100,200)
print(np.sum(x))

14950


In [ ]:
np.linspace(0,19,4)

array([ 0.        ,  6.33333333, 12.66666667, 19.        ])

In [ ]:
b = np.array([1,2,4,6])
np.mean(b)


np.float64(3.25)

In [ ]:
np.median(b)

np.float64(3.0)

In [ ]:
print(np.std(b))


1.920286436967152


In [ ]:
print(np.var(b))

3.6875


In [ ]:
z = np.array([4])
print(np.square(z))

[16]


In [ ]:
print(np.sqrt(z))

[2.]


In [ ]:
np.max(b)

np.int64(6)

In [ ]:
np.min(b)

np.int64(1)

because array sized is fixed

In [ ]:
c=np.array([[1,8,3,4],[3,7,8,9],[2,4,5,7]])
c.reshape(3,4)

array([[1, 8, 3, 4],
       [3, 7, 8, 9],
       [2, 4, 5, 7]])

indexing


In [ ]:
numbers = [10,20,30,40,50]
print(numbers[3])
print(numbers[-1])


40
50


In [ ]:
print(numbers[1:3])

[20, 30]


In [ ]:
f = np.array([3,5,6,7])
h = np.array([7,8,9,3])
print(f+h)

[10 13 15 10]


In [ ]:
print(h - f)

[ 4  3  3 -4]


In [ ]:
print(f*h)

[21 40 54 21]


In [ ]:
print(f**h)

[    2187   390625 10077696      343]


2d indexing

In [ ]:
g = np.array([[1,2,3],
               [4,5,6],
                [9,5,9]])
print(g[2,2])

5
